name: bp_Sketching
favicon: null
layout_spectrum: 0.49564476567320526
typography_spectrum: 0.7765753853600472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.32051360816694796
  lightness: 0.9115494941361248
  saturation: 0.747490378562361
  rhythmicContrast: 0.9982206837739795
purpose: []
