name: bp_Sketching
favicon: null
layout_spectrum: 0.33326
typography_spectrum: 0.26287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0e0f10'
    - '#646f77'
    - '#c5c5c5'
    - '#899197'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
